fix: add support for node-sass 7
webpack-contrib/sass-loader pull request #1072
Opened 2022-07-01 12:53 UTC by julienma

This PR contains a:

- [x] **bugfix**
- [ ] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

https://github.com/webpack-contrib/sass-loader/pull/1002 was incomplete (I guess? because it wasn't working for me, and with this change it does).

With:
```
    "node-sass": "^7.0.0",
    "sass-loader": "^10.3.0",
```

Got error:
```
ERROR in ./app/app.global.scss (./node_modules/css-loader/dist/cjs.js??ref--8-1!./node_modules/sass-loader/dist/cjs.js!./app/app.global.scss)
Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Node Sass version 7.0.1 is incompatible with ^4.0.0 || ^5.0.0 || ^6.0.0.
 @ ./app/app.global.scss 2:26-145 43:4-64:5 46:18-137
 @ ./app/index.js
 @ multi react-hot-loader/patch webpack-dev-server/client?http://localhost:1212/ webpack/hot/only-dev-server ./app/index.js
N
```

### Breaking Changes

### Additional Info

2022-07-01 13:00 UTC, julienma commented
@snitin315 CLA done.

2022-07-01 13:07 UTC, snitin315 requested changes
Is this not working with the latest version v13 as well?

2022-07-01 13:09 UTC, julienma commented
Don't know, I'm stuck on v10 due to other deps (mainly webpack 4).

2022-07-01 14:42 UTC, alexander-akait approved these changes

2022-07-01 14:42 UTC, merged

2022-07-04 18:24 UTC, alexander-akait commented
@julienma Hello, sorry for delay, today

2022-07-05 09:45 UTC, julienma commented
@alexander-akait great, waiting for it :) Thank you!

2022-07-07 10:14 UTC, julienma commented
Thanks for the release!