perf: prefer `sass-embedded` if available
webpack-contrib/sass-loader pull request #1211
Opened 2024-07-20 20:27 UTC by G-Rath

This PR contains a:

- [ ] **bugfix**
- [x] new **feature**
- [ ] **code refactor**
- [ ] **test update** 
- [ ] **typo fix**
- [ ] **metadata update**

### Motivation / Use-Case

[The Sass team considers `sass-embedded` to be stable and production-ready](https://github.com/webpack-contrib/sass-loader/issues/1180#issuecomment-2237851483), so by preferring it over `sass` developers can use `optionalDependencies` to take advantage of the more performant variant whenever possible without having to explicitly determine that for themselves.

Resolves #1180

### Breaking Changes

My understanding is that `sass-embedded` is a drop-in replacement, meaning this should not be a breaking change, though would appreciate input from @nex3 to confirm this is true enough to make this technically-not-breaking

2024-07-21 20:17 UTC, G-Rath commented
The uncovered lines are not new, and don't seem to be easily covered as [jest makes it a lot of work to mock `require.resolve`](https://github.com/jestjs/jest/issues/9543)

2024-07-22 16:08 UTC, evenstensberg approved these changes
This looks good.

2024-07-23 13:51 UTC, alexander-akait requested changes
Sorry, we can't merge it right now, because it is a breaking change, I want t have a little bit more time to test `sass-embedded` in the wild, but I am fine with such changes

2024-07-23 13:52 UTC, alexander-akait commented
Oh, looks like we need to do it due https://github.com/webpack-contrib/sass-loader/issues/1210, thank you

2024-07-23 13:53 UTC, alexander-akait approved these changes

2024-07-23 14:03 UTC, merged